### ISSUE TITLE
OpenApi and https behind reverse proxy

### ISSUE THREAD

**Issue by Censacrof** [unicom-project-eu/wp6-db-api#3]
Swagger gives an error if https is enabled:

![image](https://user-images.githubusercontent.com/15619279/200361623-7a5dbe3b-0dc5-4e40-a636-822befd354a1.png)

Searching online, a workaround is to add
```yaml
schemes:
  - https
```
to the OpenApi configuration. We need to find a way of doing this using the Java api.

**Comment by p-pierantozzi** [comment]
#https://github.com/unicom-project-eu/wp6-db-api/commit/49df1f2622efc03e8202c053bb5fd1631e9cf923
