### ISSUE TITLE
Use BundleBuilder in ResourceProviders

### ISSUE THREAD

**Issue by Censacrof** [unicom-project-eu/wp6-db-api#5]
In resource providers, see if is possible to use of the [BundleBuilder](https://hapifhir.io/hapi-fhir/docs/model/bundle_builder.html) instead of anonymous IBoundleProvider classes.

**Comment by p-pierantozzi** [comment]
Closed, as after checking the documentation, it seems that BundleBuilder and IBoundleProvider
